# Generated by Django 5.1.2 on 2024-10-30 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_rename_game_img_name_games_game_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_catergory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.cartergory'),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
