# Generated by Django 5.1.2 on 2024-10-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_games_game_catergory_alter_games_game_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
