# Generated by Django 5.1.2 on 2024-11-27 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_remove_games_game_catergory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='base_view',
            field=models.ImageField(blank=True, null=True, upload_to='./media/games', verbose_name='Game Image'),
        ),
        migrations.AlterField(
            model_name='games',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.category', verbose_name='Category ID'),
        ),
        migrations.CreateModel(
            name='GamePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_img', models.ImageField(upload_to='./media/games', verbose_name='Game image')),
                ('game_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.games', verbose_name='Product ID')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductPicture',
        ),
    ]
