# Generated by Django 5.1.2 on 2024-11-30 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_games_base_view_alter_games_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gamepicture',
            name='game_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.games', verbose_name='Game ID'),
        ),
    ]
