# Generated by Django 5.1.2 on 2024-12-23 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_games_discount_percent_games_final_game_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Image'),
        ),
    ]
