# Generated by Django 5.1.2 on 2024-12-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='category_id',
        ),
        migrations.AddField(
            model_name='games',
            name='category_id',
            field=models.ManyToManyField(blank=True, null=True, to='games.category', verbose_name='Category ID'),
        ),
    ]
