# Generated by Django 5.1.2 on 2024-12-27 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_remove_games_category_id_games_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.games', verbose_name='game_id')),
            ],
        ),
    ]
