# Generated by Django 5.1.2 on 2024-12-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_gamecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecode',
            name='is_used',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
