# Generated by Django 5.1.2 on 2024-12-30 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_alter_gamecode_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='category_id',
        ),
        migrations.AddField(
            model_name='games',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.category', verbose_name='Category ID'),
        ),
    ]
