# Generated by Django 5.1.2 on 2024-12-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_remove_games_category_id_games_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='category_id',
        ),
        migrations.AddField(
            model_name='games',
            name='category_id',
            field=models.ManyToManyField(blank=True, to='games.category', verbose_name='Category ID'),
        ),
    ]
