# Generated by Django 5.1.2 on 2024-12-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_remove_games_category_id_games_category_id'),
        ('user', '0004_cart_id_alter_cart_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bought_category',
            field=models.ManyToManyField(blank=True, to='games.category', verbose_name='Bough Category'),
        ),
    ]
